version: '3.3'
services:
  jenkins:
    build:
      context: .
      dockerfile: builds/custom-jenkins-python-310.Dockerfile
    user: root
    ports:
      - 6061:8080
    volumes:
      - ./jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
